In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [2]:
df = pd.read_csv('cars_train.csv', encoding='utf_16', sep='\t')

In [3]:
df_test = pd.read_csv('cars_test.csv', encoding='utf_16', sep='\t')

In [4]:
df_test.dtypes

id                          object
num_fotos                  float64
marca                       object
modelo                      object
versao                      object
ano_de_fabricacao            int64
ano_modelo                 float64
hodometro                  float64
cambio                      object
num_portas                   int64
tipo                        object
blindado                    object
cor                         object
tipo_vendedor               object
cidade_vendedor             object
estado_vendedor             object
anunciante                  object
entrega_delivery              bool
troca                         bool
elegivel_revisao              bool
dono_aceita_troca           object
veiculo_único_dono          object
revisoes_concessionaria     object
ipva_pago                   object
veiculo_licenciado          object
garantia_de_fábrica         object
revisoes_dentro_agenda      object
veiculo_alienado           float64
dtype: object

In [5]:
df.columns[df.isna().any()].tolist()

['num_fotos',
 'dono_aceita_troca',
 'veiculo_único_dono',
 'revisoes_concessionaria',
 'ipva_pago',
 'veiculo_licenciado',
 'garantia_de_fábrica',
 'revisoes_dentro_agenda',
 'veiculo_alienado']

In [6]:
df = df.fillna(0)
df_test = df_test.fillna(0)

In [7]:
df

,id,num_fotos,marca,modelo,versao,ano_de_fabricacao,ano_modelo,hodometro,cambio,num_portas,...,elegivel_revisao,dono_aceita_troca,veiculo_único_dono,revisoes_concessionaria,ipva_pago,veiculo_licenciado,garantia_de_fábrica,revisoes_dentro_agenda,veiculo_alienado,preco
0,300716223898539419613863097469899222392,8.0,NISSAN,KICKS,1.6 16V FLEXSTART SL 4P XTRONIC,2017,2017.0,67772.0,CVT,4,...,False,0,0,Todas as revisões feitas pela concessionária,IPVA pago,Licenciado,0,0,0.0,74732.590084
1,279639842134129588306469566150288644214,8.0,JEEP,COMPASS,2.0 16V FLEX LIMITED AUTOMÁTICO,2017,2017.0,62979.0,Automática,4,...,False,Aceita troca,0,0,IPVA pago,0,0,0,0.0,81965.332634
2,56414460810621048900295678236538171981,16.0,KIA,SORENTO,2.4 16V GASOLINA EX 7L AWD AUTOMÁTICO,2018,2019.0,44070.0,Automática,4,...,False,Aceita troca,0,0,0,0,0,0,0.0,162824.814472
3,56862509826849933428086372390159405545,14.0,VOLKSWAGEN,AMAROK,2.0 HIGHLINE 4X4 CD 16V TURBO INTERCOOLER DIES...,2013,2015.0,85357.0,Automática,4,...,False,Aceita troca,0,0,IPVA pago,Licenciado,0,0,0.0,123681.358857
4,338980975753200343894519909855598027197,8.0,SSANGYONG,KORANDO,2.0 GLS 4X4 16V TURBO DIESEL 4P AUTOMÁTICO,2013,2015.0,71491.0,Automática,4,...,False,0,0,Todas as revisões feitas pela concessionária,0,0,Garantia de fábrica,Todas as revisões feitas pela agenda do carro,0.0,82419.763891
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29579,40985083650499509711752444068313401704,8.0,TOYOTA,HILUX,2.8 D-4D TURBO DIESEL CD SRX 4X4 AUTOMÁTICO,2021,2021.0,8150.0,Automática,4,...,False,Aceita troca,Único dono,0,IPVA pago,Licenciado,Garantia de fábrica,0,0.0,403015.289616
29580,164663177589009976281210123914772747797,8.0,VOLKSWAGEN,POLO,1.0 200 TSI HIGHLINE AUTOMÁTICO,2020,2020.0,17987.0,Automática,4,...,False,0,Único dono,Todas as revisões feitas pela concessionária,IPVA pago,Licenciado,Garantia de fábrica,0,0.0,88978.080497
29581,170866287186047465472146212778882034162,8.0,TOYOTA,HILUX,2.8 SRX 4X4 CD 16V DIESEL 4P AUTOMÁTICO,2019,2019.0,44742.0,Automática,4,...,False,Aceita troca,0,0,0,0,0,0,0.0,218807.648664
29582,208909739337040262669325459666578363437,8.0,PEUGEOT,2008,1.6 16V FLEX ALLURE PACK 4P AUTOMÁTICO,2021,2022.0,35376.0,Automática,4,...,False,Aceita troca,Único dono,0,IPVA pago,Licenciado,0,0,0.0,68495.990693
29583,171781413417552881896009715888472310172,14.0,AUDI,Q7,3.0 TFSI AMBIENTE V6 24V GASOLINA 4P TIPTRONIC,2016,2017.0,90433.0,Automática,4,...,False,Aceita troca,0,0,0,0,0,0,0.0,132507.873187

In [8]:
df_test

,id,num_fotos,marca,modelo,versao,ano_de_fabricacao,ano_modelo,hodometro,cambio,num_portas,...,troca,elegivel_revisao,dono_aceita_troca,veiculo_único_dono,revisoes_concessionaria,ipva_pago,veiculo_licenciado,garantia_de_fábrica,revisoes_dentro_agenda,veiculo_alienado
0,13518783164498355150900635905895481162,8.0,NISSAN,VERSA,1.6 16V FLEXSTART V-DRIVE MANUAL,2021,2021.0,20258.0,Manual,4,...,False,False,Aceita troca,0,0,IPVA pago,Licenciado,Garantia de fábrica,0,0.0
1,299896161723793383246777788797566040330,18.0,FIAT,STRADA,1.4 MPI WORKING CS 8V FLEX 2P MANUAL,2021,2021.0,53045.0,Manual,2,...,False,False,Aceita troca,Único dono,0,IPVA pago,Licenciado,0,0,0.0
2,316180649972302128246133616457018378621,8.0,AUDI,Q5,2.0 TFSI GASOLINA BLACK S TRONIC,2018,2019.0,32486.0,Automática,4,...,False,False,Aceita troca,0,0,IPVA pago,0,0,0,0.0
3,222527157104148385909188217274642813298,16.0,CHEVROLET,CRUZE,1.4 TURBO LT 16V FLEX 4P AUTOMÁTICO,2019,2020.0,24937.0,Automática,4,...,False,False,Aceita troca,Único dono,0,IPVA pago,Licenciado,0,0,0.0
4,160460343059850745858546502614838368036,8.0,FORD,ECOSPORT,1.5 TI-VCT FLEX SE AUTOMÁTICO,2019,2019.0,62074.0,Automática,4,...,False,False,Aceita troca,0,0,IPVA pago,Licenciado,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9857,270530958308663978454359593206239054667,8.0,TOYOTA,COROLLA,1.8 GLI UPPER 16V FLEX 4P AUTOMÁTICO,2017,2018.0,44943.0,CVT,4,...,False,False,0,0,0,IPVA pago,Licenciado,0,0,0.0
9858,35444226755331218706378362485070904721,17.0,TOYOTA,HILUX,2.8 SRV 4X4 CD 16V DIESEL 4P AUTOMÁTICO,2017,2017.0,44316.0,Automática,4,...,False,False,Aceita troca,0,0,0,0,0,0,0.0
9859,151927592621490440610866139377092833936,8.0,CHEVROLET,TRACKER,1.0 TURBO FLEX LT AUTOMÁTICO,2020,2021.0,21587.0,Automática,4,...,False,False,0,Único dono,Todas as revisões feitas pela concessionária,IPVA pago,0,Garantia de fábrica,0,0.0
9860,118047837484645467440786911677256539035,9.0,PEUGEOT,2008,1.6 16V FLEX ALLURE PACK 4P AUTOMÁTICO,2018,2018.0,54084.0,Automática,4,...,False,False,Aceita troca,Único dono,0,IPVA pago,Licenciado,0,0,0.0
9861,332784980027104367393384305973418103109,8.0,TOYOTA,HILUX,2.8 SRX 4X4 CD 16V DIESEL 4P AUTOMÁTICO,2019,2020.0,32511.0,Automática,4,...,False,False,Aceita troca,0,Todas as revisões feitas pela concessionária,0,0,0,0,0.0

In [9]:
# retirando variáveis redundantes
df = df.drop(columns=['veiculo_alienado', 'elegivel_revisao', 'versao', 'cidade_vendedor'])
df_test = df_test.drop(columns=['veiculo_alienado', 'elegivel_revisao', 'versao', 'cidade_vendedor'])

In [10]:
#padronizando variaveis numericas
df[['num_fotos','ano_modelo', 'hodometro']] = df[['num_fotos','ano_modelo', 'hodometro']].astype(int)
df_test[['num_fotos','ano_modelo', 'hodometro']] = df_test[['num_fotos','ano_modelo', 'hodometro']].astype(int)

In [11]:
df['preco'] = df['preco'].round(2)

In [12]:
df = df.replace(to_replace=['Aceita troca', 'Único dono', 'Todas as revisões feitas pela concessionária', 'IPVA pago', 'Licenciado', 'Garantia de fábrica', 'Todas as revisões feitas pela agenda do carro'], value=1)
df['blindado'] = df['blindado'].replace({'N': 0, 'S': 1})
df_test = df_test.replace(to_replace=['Aceita troca', 'Único dono', 'Todas as revisões feitas pela concessionária', 'IPVA pago', 'Licenciado', 'Garantia de fábrica', 'Todas as revisões feitas pela agenda do carro'], value=1)
df_test['blindado'] = df_test['blindado'].replace({'N': 0, 'S': 1})

In [13]:
df['tipo_vendedor'] = df['tipo_vendedor'].map({'PF': True, 'PJ': False})
df = df.rename(columns={'tipo_vendedor': 'vendedor_PF'})
df_test['tipo_vendedor'] = df_test['tipo_vendedor'].map({'PF': True, 'PJ': False})
df_test = df_test.rename(columns={'tipo_vendedor': 'vendedor_PF'})

##### Limpando df_test

In [14]:
set(df_test['modelo']) - set(df['modelo'])

{'323i',
 'CALIFORNIA',
 'CLS 500',
 'CLS 63 AMG',
 'GRANTURISMO',
 'HURACÁN',
 'M 140i',
 'OPTIMA',
 'PAMPA',
 'PARATI',
 'QQ',
 'R8',
 'S 63 AMG',
 'TIGGO',
 'X-TYPE',
 'XJ'}

In [15]:
set(df['estado_vendedor']) - set(df_test['estado_vendedor'])

{'Maranhão (MA)'}

In [16]:
df_test = df_test.drop(df_test[df_test.modelo.isin(['323i','CALIFORNIA','CLS 500','CLS 63 AMG','GRANTURISMO','HURACÁN','M 140i','OPTIMA','PAMPA','PARATI','QQ','R8','S 63 AMG','TIGGO','X-TYPE','XJ'])].index)

In [17]:
df = df.drop(df[df.modelo.isin(['118i', '147', '218i', '225i', '316i', '330e', '335i', '407', '420i', '5008', '530', '530e', '545i', '640i', '745Le', 'A 190', 'ACCORD', 'AGILE', 'AIRTREK', 'AMG GT 63', 'B 180', 'BOXER', 'BRAVO', 'C 180 K', 'C 230 K', 'C 240', 'C 350', 'C30', 'C4 GRAND PICASSO', 'CARAVAN', 'CLA 35 AMG', 'CLC 200 K', 'CLS 450', 'CLS 53 AMG', 'DAILY', 'DS4', 'ECLIPSE', 'ES', 'ES 300h', 'ES 350', 'ESCORT', 'ETIOS CROSS', 'F-1000', 'F360', 'GL 63 AMG', 'GLC 63 AMG', 'GLE 350', 'GLE 400d', 'GLK 300', 'GRAND BLAZER', 'I30 CW', 'KANGOO', 'L200', 'L200 SAVANA', 'LINEA', 'M-11', 'M5', 'MALIBU', 'ML 320', 'PARTNER', 'PASEO', 'PASSAT VARIANT', 'POLO SEDAN', 'Q8', 'QUATTROPORTE', 'RCZ', 'RS3', 'RS4', 'RS7', 'RX 450h', 'S 500 L', 'S 55 AMG', 'S4', 'S6', 'S80', 'S90', 'SANTANA', 'SLK 230', 'SLK 55 AMG', 'SONATA', 'SPACE CROSS', 'STILO', 'SX4', 'SYMBOL', 'T60', 'TIIDA', 'TRANSIT', 'V70', 'X-TRAIL', 'X7', 'X80', 'XTERRA', 'Z3', 'ZOE', 'i8'])].index)

In [18]:
df_test = df_test.drop(df_test[df_test.cor.isin(['Azul'])].index)

In [19]:
df = df.drop(df[df.cor.isin(['Verde', 'Vermelho'])].index)

In [20]:
df_test = df_test.drop(df_test[df_test.tipo.isin(['Conversível'])].index)

In [21]:
df_test = df_test.drop(df_test[df_test.marca.isin(['LAMBORGHINI'])].index)

In [22]:
df = df.drop(df[df.estado_vendedor.isin(['Maranhão (MA)'])].index)

##### Normalização e Padronização

In [23]:
variaveis_normalizar = ['num_fotos', 'num_portas', 'ano_de_fabricacao', 'ano_modelo']
variaveis_padronizar = ['hodometro']

In [24]:
scaler_norm = MinMaxScaler()
scaler_std = StandardScaler()

In [25]:
df[variaveis_normalizar] = scaler_norm.fit_transform(df[variaveis_normalizar])
df[variaveis_padronizar] = scaler_std.fit_transform(df[variaveis_padronizar])

df_test[variaveis_normalizar] = scaler_norm.fit_transform(df_test[variaveis_normalizar])
df_test[variaveis_padronizar] = scaler_std.fit_transform(df_test[variaveis_padronizar])

In [26]:
numeric_cols = ['num_fotos', 'ano_de_fabricacao', 'ano_modelo', 'hodometro', 'num_portas']
df[numeric_cols].describe()

,num_fotos,ano_de_fabricacao,ano_modelo,hodometro,num_portas
count,29355.000000,29355.000000,29355.000000,2.935500e+04,29355.000000
mean,0.488856,0.859361,0.801060,-4.066468e-17,0.970840
std,0.169915,0.108217,0.102308,1.000017e+00,0.167802
min,0.000000,0.000000,0.000000,-1.798722e+00,0.000000
25%,0.380952,0.810811,0.730769,-8.371602e-01,1.000000
50%,0.380952,0.891892,0.807692,-3.018266e-02,1.000000
75%,0.666667,0.945946,0.884615,7.263897e-01,1.000000
max,1.000000,1.000000,1.000000,9.915772e+00,1.000000

In [27]:
df_test[numeric_cols].describe()

         num_fotos  ano_de_fabricacao   ano_modelo     hodometro   num_portas
count  9841.000000        9841.000000  9841.000000  9.841000e+03  9841.000000
mean      0.488602           0.845048     0.675643 -6.714813e-17     0.971598
std       0.168716           0.121448     0.167085  1.000051e+00     0.165896
min       0.000000           0.000000     0.000000 -1.792014e+00     0.000000
25%       0.380952           0.794118     0.562500 -8.282393e-01     1.000000
50%       0.380952           0.882353     0.687500 -4.579842e-02     1.000000
75%       0.666667           0.911765     0.812500  7.259122e-01     1.000000
max       1.000000           1.000000     1.000000  9.975063e+00     1.000000

#### Análise Exploratória

In [28]:
df['marca'].unique()
marcas = df.query("marca in ('NISSAN', 'VOLKSWAGEN', 'HYUNDAI', 'HONDA', 'TOYOTA', 'MITSUBISHI', 'CHEVROLET', 'FORD', 'PEUGEOT', 'RENAULT', 'FIAT')")

In [29]:
estados_total = marcas.groupby(marcas['estado_vendedor'])['preco'].sum().reset_index(name='Total').sort_values(['Total'], ascending=False)
pd.set_option('display.float_format', '{:.2f}'.format)
estados_q = marcas.groupby(marcas['estado_vendedor'])['preco'].count().reset_index(name='Quantidade').sort_values(['Quantidade'], ascending=False)

estados = pd.merge(estados_total, estados_q, on=["estado_vendedor"])
estados['Média'] = estados['Total'] / estados['Quantidade']
estados.sort_values(['Média'], ascending=False)

             estado_vendedor         Total  Quantidade     Média
21                Piauí (PI)    1062716.71           6 177119.45
16              Sergipe (SE)    2992526.27          17 176030.96
14          Mato Grosso (MT)    4317339.55          31 139269.02
6                 Goiás (GO)   69401821.91         524 132446.23
2                Paraná (PR)  197224046.19        1582 124667.54
9               Alagoas (AL)   14552252.08         117 124378.22
5     Rio Grande do Sul (RS)  124882618.49        1029 121363.09
18            Tocantins (TO)    2257144.34          19 118797.07
4          Minas Gerais (MG)  138885810.55        1170 118705.82
22             Rondônia (RO)     473455.28           4 118363.82
11                 Pará (PA)    8154349.03          69 118178.97
1        Rio de Janeiro (RJ)  197477134.40        1712 115348.79
7                 Bahia (BA)   50172648.03         445 112747.52
3        Santa Catarina (SC)  164289357.78        1472 111609.62
12  Rio Grande do Norte (RN)    7954739.90          73 108969.04
0             São Paulo (SP) 1200025314.79       11040 108697.95
13                Ceará (CE)    6547766.98          63 103932.81
8            Pernambuco (PE)   23362053.63         228 102465.15
17   Mato Grosso do Sul (MS)    2739669.79          27 101469.25
19       Espírito Santo (ES)    2027221.87          21  96534.37
10              Paraíba (PB)    9235614.90         100  92356.15
20                 Acre (AC)    1905329.30          21  90729.97
15             Amazonas (AM)    4132005.86          49  84326.65
23              Roraima (RR)     127227.39           2  63613.69

In [30]:
df['cambio'].unique()
picape_cambio = df[(df['tipo']=='Picape') & (df['cambio']=='Automática')]
picape_cambio

,id,num_fotos,marca,modelo,ano_de_fabricacao,ano_modelo,hodometro,cambio,num_portas,tipo,...,entrega_delivery,troca,dono_aceita_troca,veiculo_único_dono,revisoes_concessionaria,ipva_pago,veiculo_licenciado,garantia_de_fábrica,revisoes_dentro_agenda,preco
3,56862509826849933428086372390159405545,0.67,VOLKSWAGEN,AMAROK,0.76,0.69,0.84,Automática,1.00,Picape,...,True,True,1,0,0,1,1,0,0,123681.36
48,288950486904285252834098132344068709579,0.38,VOLKSWAGEN,GOLF,0.76,0.69,0.10,Automática,1.00,Picape,...,False,False,0,0,1,1,1,0,1,86304.70
61,35429253802991633165448719135914498665,0.38,FIAT,TORO,0.86,0.77,1.34,Automática,1.00,Picape,...,False,False,1,0,0,0,0,0,0,89522.64
65,328880961834833259252462744533448193192,0.76,MINI,COOPER,0.76,0.65,-1.76,Automática,0.00,Picape,...,False,False,1,0,0,0,0,0,0,217524.35
79,46988346268821185308430847707885811630,0.38,MERCEDES-BENZ,CLS 350,0.76,0.65,1.10,Automática,1.00,Picape,...,False,False,0,0,1,1,1,0,1,364010.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29561,208180790102132584532337225991122989286,0.38,VOLKSWAGEN,AMAROK,0.89,0.85,-1.10,Automática,1.00,Picape,...,False,False,1,0,0,0,0,0,0,199812.08
29572,170645989328963286918664514464521878796,0.38,RAM,2500,0.84,0.81,-0.89,Automática,1.00,Picape,...,False,False,1,0,0,1,1,0,0,257978.02
29579,40985083650499509711752444068313401704,0.38,TOYOTA,HILUX,0.97,0.92,-1.55,Automática,1.00,Picape,...,False,False,1,1,0,1,1,1,0,403015.29
29580,164663177589009976281210123914772747797,0.38,VOLKSWAGEN,POLO,0.95,0.88,-1.25,Automática,1.00,Picape,...,False,False,0,1,1,1,1,1,0,88978.08
29581,170866287186047465472146212778882034162,0.38,TOYOTA,HILUX,0.92,0.85,-0.42,Automática,1.00,Picape,...,False,False,1,0,0,0,0,0,0,218807.65

In [31]:
picape_cambio_t = picape_cambio.groupby(picape_cambio['estado_vendedor'])['preco'].sum().reset_index(name='Total').sort_values(['Total'], ascending=False)
pd.set_option('display.float_format', '{:.2f}'.format)
picape_cambio_q = picape_cambio.groupby(picape_cambio['estado_vendedor'])['preco'].count().reset_index(name='Quantidade').sort_values(['Quantidade'], ascending=False)

estados_p_c = pd.merge(picape_cambio_t, picape_cambio_q, on=["estado_vendedor"])
estados_p_c['Média'] = estados_p_c['Total'] / estados_p_c['Quantidade']
estados_p_c.sort_values(['Média'], ascending=True)

             estado_vendedor        Total  Quantidade     Média
16              Paraíba (PB)    372628.14           4  93157.04
14   Mato Grosso do Sul (MS)    723501.24           5 144700.25
12                 Acre (AC)    871540.17           6 145256.69
17  Rio Grande do Norte (RN)    179961.69           1 179961.69
2        Rio de Janeiro (RJ)  57767989.57         318 181660.34
3        Santa Catarina (SC)  52430236.17         282 185922.82
15            Tocantins (TO)    563151.39           3 187717.13
0             São Paulo (SP) 320766918.87        1699 188797.48
8            Pernambuco (PE)   2695934.70          14 192566.76
4          Minas Gerais (MG)  41293315.02         211 195702.91
5     Rio Grande do Sul (RS)  38603665.02         197 195957.69
1                Paraná (PR)  68026395.91         343 198327.68
7                 Bahia (BA)  13873094.71          67 207061.12
6                 Goiás (GO)  21231673.18         102 208153.66
13                Piauí (PI)    832724.31           4 208181.08
10          Mato Grosso (MT)   1284613.91           6 214102.32
9               Alagoas (AL)   2624058.51          12 218671.54
11              Sergipe (SE)   1198482.80           4 299620.70

In [32]:
garantia = df.loc[df['garantia_de_fábrica'] == 1]
garantia

,id,num_fotos,marca,modelo,ano_de_fabricacao,ano_modelo,hodometro,cambio,num_portas,tipo,...,entrega_delivery,troca,dono_aceita_troca,veiculo_único_dono,revisoes_concessionaria,ipva_pago,veiculo_licenciado,garantia_de_fábrica,revisoes_dentro_agenda,preco
4,338980975753200343894519909855598027197,0.38,SSANGYONG,KORANDO,0.76,0.69,0.41,Automática,1.00,Utilitário esportivo,...,False,False,0,0,1,0,0,1,1,82419.76
8,27193355972239090268287282344066791959,0.38,VOLKSWAGEN,UP,0.86,0.81,-0.57,Manual,1.00,Sedã,...,False,False,0,1,1,1,1,1,1,75088.72
17,22623637632558238619093107555320587591,0.38,VOLKSWAGEN,POLO,0.92,0.85,-0.71,Automática,1.00,Hatchback,...,False,False,0,1,0,1,1,1,0,52375.52
19,118295225597332705218254827343258102397,0.38,CHEVROLET,ONIX,0.97,0.96,-1.58,Manual,1.00,Utilitário esportivo,...,False,False,0,1,1,1,1,1,1,148360.04
21,161689246994150584328334702158353189075,0.38,PORSCHE,CAYENNE,0.95,0.88,-1.55,Automática,1.00,Utilitário esportivo,...,False,False,1,0,1,1,1,1,1,377512.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29564,7153831053306885937235229425685159881,0.38,VOLKSWAGEN,GOL,0.97,0.92,-1.15,Automática,1.00,Hatchback,...,False,False,0,1,1,1,1,1,1,199455.69
29566,264948049948751322976294662307060386869,0.38,FIAT,STRADA,0.97,0.96,-1.72,Manual,1.00,Hatchback,...,False,False,0,1,0,1,1,1,0,92239.27
29567,148783390470394554026358945089096197309,0.38,JEEP,RENEGADE,0.92,0.88,-0.84,Automática,1.00,Sedã,...,False,False,0,1,1,1,1,1,1,55605.00
29579,40985083650499509711752444068313401704,0.38,TOYOTA,HILUX,0.97,0.92,-1.55,Automática,1.00,Picape,...,False,False,1,1,0,1,1,1,0,403015.29
29580,164663177589009976281210123914772747797,0.38,VOLKSWAGEN,POLO,0.95,0.88,-1.25,Automática,1.00,Picape,...,False,False,0,1,1,1,1,1,0,88978.08

In [33]:
garantia_t = garantia.groupby(garantia['estado_vendedor'])['preco'].sum().reset_index(name='Total').sort_values(['Total'], ascending=False)
pd.set_option('display.float_format', '{:.2f}'.format)
garantia_q = garantia.groupby(garantia['estado_vendedor'])['preco'].count().reset_index(name='Quantidade').sort_values(['Quantidade'], ascending=False)

estados_g = pd.merge(garantia_t, garantia_q, on=["estado_vendedor"])
estados_g['Média'] = estados_g['Total'] / estados_g['Quantidade']
estados_g.sort_values(['Média'], ascending=True)

             estado_vendedor        Total  Quantidade     Média
20              Paraíba (PB)     95762.75           1  95762.75
10                 Pará (PA)   1668662.48          17  98156.62
15             Amazonas (AM)    896555.73           9  99617.30
14       Espírito Santo (ES)    936271.88           9 104030.21
11   Mato Grosso do Sul (MS)   1582224.65          13 121709.59
19                Ceará (CE)    123939.88           1 123939.88
12  Rio Grande do Norte (RN)   1198083.55           9 133120.39
9            Pernambuco (PE)   2997968.35          20 149898.42
17                 Acre (AC)    300833.83           2 150416.91
7               Alagoas (AL)   8947583.24          58 154268.68
5          Minas Gerais (MG)  42558456.28         264 161206.27
8                 Bahia (BA)   8081928.01          50 161638.56
0             São Paulo (SP) 379969993.90        2288 166070.80
3        Santa Catarina (SC)  57353485.12         330 173798.44
6                 Goiás (GO)  32460982.82         186 174521.41
4     Rio Grande do Sul (RS)  48809064.11         279 174942.88
2                Paraná (PR)  67830257.32         387 175271.98
1        Rio de Janeiro (RJ)  73793261.55         412 179109.86
16          Mato Grosso (MT)    395314.14           2 197657.07
18            Tocantins (TO)    243002.22           1 243002.22
13              Sergipe (SE)   1101415.30           3 367138.43

##### One-hot_encoding

In [34]:
## Selecionando as variaveis categoricas para realizar o one-hot-encoding
categorical_cols = ['marca', 'modelo', 'cambio', 'tipo', 'blindado', 'cor', 'vendedor_PF', 'estado_vendedor', 'anunciante', 'entrega_delivery', 'troca', 'dono_aceita_troca', 'veiculo_único_dono', 'revisoes_concessionaria', 'ipva_pago', 'veiculo_licenciado', 'garantia_de_fábrica', 'revisoes_dentro_agenda']  # substitua 'categoria' pelo nome da sua coluna categórica

one_hot_encoded = pd.get_dummies(df[categorical_cols])
data_encoded = pd.concat([df, one_hot_encoded], axis=1)
data_encoded = data_encoded.drop(categorical_cols, axis=1)

In [35]:
one_hot_encoded_test = pd.get_dummies(df_test[categorical_cols])
data_encoded_test = pd.concat([df_test, one_hot_encoded_test], axis=1)
data_encoded_test = data_encoded_test.drop(categorical_cols, axis=1)

#### Correlação das variáveis com o preço

In [36]:
# Create correlation matrix
corr_matrix = data_encoded.corr().abs()

In [37]:
corr_preco = corr_matrix["preco"]
corr_preco.sort_values(ascending=False).head(60)

preco                       1.00
tipo_Utilitário esportivo   0.41
hodometro                   0.36
cambio_Manual               0.29
cambio_Automática           0.29
marca_PORSCHE               0.25
ano_de_fabricacao           0.23
tipo_Hatchback              0.22
ano_modelo                  0.21
marca_BMW                   0.21
tipo_Sedã                   0.20
cor_Cinza                   0.19
marca_LAND ROVER            0.18
marca_RAM                   0.18
modelo_2500                 0.17
modelo_HILUX                0.17
marca_CHEVROLET             0.17
marca_HYUNDAI               0.16
tipo_Picape                 0.14
modelo_MACAN                0.14
modelo_DISCOVERY            0.13
modelo_718                  0.13
modelo_RANGE ROVER VELAR    0.11
cor_Prata                   0.11
modelo_PAJERO FULL          0.11
marca_MERCEDES-BENZ         0.11
marca_FIAT                  0.11
modelo_M3                   0.11
modelo_ONIX                 0.10
tipo_Cupê                   0.10
modelo_CAYENNE              0.10
modelo_320i                 0.10
modelo_911                  0.10
modelo_HB20                 0.10
marca_HONDA                 0.09
modelo_AMAROK               0.09
anunciante_Loja             0.09
modelo_MUSTANG              0.09
anunciante_Pessoa Física    0.09
modelo_RANGE ROVER SPORT    0.09
modelo_HILUX SW4            0.09
modelo_STRADA               0.09
marca_RENAULT               0.08
modelo_PANAMERA             0.08
modelo_POLO                 0.08
modelo_MONTANA              0.08
modelo_DISCOVERY SPORT      0.08
marca_TOYOTA                0.08
modelo_C 63 AMG             0.08
marca_VOLKSWAGEN            0.08
modelo_CRUZE                0.08
marca_VOLVO                 0.08
marca_AUDI                  0.08
modelo_VIRTUS               0.08
num_portas                  0.08
modelo_RANGER               0.08
marca_JAGUAR                0.08
modelo_FIT                  0.08
modelo_HB20S                0.07
modelo_X1                   0.07
Name: preco, dtype: float64

### Testando o modelo

In [38]:
#df_train = data_encoded.drop('preco', axis=1)
#target = data_encoded['preco']

In [39]:
#X_train_split, X_test_split, y_train_split, y_test_split = train_test_split(df_train, target, test_size=0.25, random_state=42)

In [40]:
#n_estimators = 200

In [41]:
#model = RandomForestRegressor(n_estimators=n_estimators)
#model.fit(X_train_split, y_train_split)

In [42]:
#y_pred = model.predict(X_test_split)

In [43]:
#from sklearn.metrics import r2_score
#r2 = r2_score(y_test_split, y_pred)
#print("R²:", r2) #R²: 0.6845100289895603

## Modelo

In [44]:
df_train = data_encoded.drop('preco', axis=1)
target = data_encoded['preco']

In [45]:
n_estimators = 200

In [46]:
model = RandomForestRegressor(n_estimators=n_estimators)
model.fit(df_train, target)

RandomForestRegressor(n_estimators=200)

In [47]:
y_pred = model.predict(data_encoded_test)

In [48]:
y_pred

array([ 58785.7999 ,  56632.4508 , 287245.4782 , ..., 106297.9517 ,
       108700.65565, 295183.5935 ])

In [50]:
data_encoded_test['preco'] = y_pred

In [51]:
df_final = data_encoded_test[['id', 'preco']]

In [53]:
df_final.to_csv('predicted.csv')

In [55]:
!pip freeze > requirements.txt  # Python3

In [56]:
!pip list --format=freeze > requirements.txt